steps:
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['-m', 'cp', '-r', '.', 'gs://$PROJECT_ID/helloworld']

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/nodejs-helloworld','.']

images: ['gcr.io/$PROJECT_ID/nodejs-helloworld']